### ISSUE TITLE
Heroku - Tentando fazer deploy

### ISSUE THREAD

**Issue by onesimoGit** [onesimoGit/MobileWebAlunos2ed#6]
![heroku-bug](https://user-images.githubusercontent.com/45593347/164278587-4ea7c910-1170-4525-973c-deba79807a72.PNG)

**Comment by tantofaznem** [comment]
**Solved**: Estava a usar uma versao diferente de Tar, mas conseguimos resolver...

**Comment by nevesantonio-pilale** [comment]
> ![heroku-bug](https://user-images.githubusercontent.com/45593347/164278587-4ea7c910-1170-4525-973c-deba79807a72.PNG)

**Comment by nevesantonio-pilale** [comment]
Problema ultrapassado estava usando o "TAR" desactualizado. passei com ajuda do colega Abd Domingos.
